### ISSUE TITLE
Make Lazy decommit on Windows Asynchronous

### ISSUE THREAD

**Issue by mjp41** [microsoft/snmalloc#127]
Lazy decommit occurs on Windows once a low-memory notification has been received, and then any thread ends up calling into the large allocator.  The decommit, is only decommiting large chunks of memory held in global datastructures, not in thread local data structures.

If an application is idle, when the low-memory notification is received nothing would happen.  Can we make the call-back actually perform the lazy-decommit. The lock-free data structures are thread safe, so this seems like it would be a win, and only a small code change.

On Windows this seems like it would be sensible. But not sure about other platforms we might want to support.  @davidchisnall do you have any thoughts on this?

**Comment by mjp41** [comment]
@buybackoff I have raised this issue as it seems like we are close to addressing your use case, but would need to make a few changes.

**Comment by davidchisnall** [comment]
Currently, only Windows, Android, and XNU support low-memory notifications and only Windows delivers them via a useful API for low-level code (on XNU, there appears to be a kqueue event for low memory, but the lowest level of published API is libdispatch, on Android the lowest-level published API is Java, though presumably there's a magic `/dev` node that you can monitor [possibly only if you're root]).  I don't think it's worth worrying too much about other platforms yet (though it might be nice to expose the notification as a callback on platforms that don't have low-level API support so that iOS and Android users can invoke it from their high-level notification).  

Is your comment in relation to the possible approach that we discussed of implementing a virtual decommit in the PAL that takes ownership of the decommitted pages but doesn't actually decommit them unless there's memory pressure?  Even if that were protected by a mutex, it would likely have significantly lower overhead than anything that involves VM subsystem interaction.

**Comment by mjp41** [comment]
I was thinking about something a little simpler initially, though, I want to follow up your idea. But it needs careful design for concurrency if we allow a more fine-grained decommit.  If we don't allow a more fine-grained decommit, then I think the approach below will be good enough.

So I was thinking of allowing the PAL to deliver async callbacks for low-memory notifications:
```
   class PalCallbackObject
   {
      PalCallbackObject* next;
      void (*process)(PalCallbackObject* );  
   };

   void register_low_memory_callback(PalCallbackObject* notify)
```
Then we register an object that will call `LargeAlloc::lazy_decommit`.  This means that even an idle process will decommit memory on Windows. Currently, we need churn to get off the fast path to trigger the pooling to see if the epoch has changed.

**Comment by davidchisnall** [comment]
Do we need changes to anything in `LargeAlloc` to support decommitting from another thread?  I can see this model fitting very well with XNU + libdispatch and even as a thing to expose to the Java APIs via JNI on Android quite cleanly.

I was also considering yesterday whether we may want to propose some new APIs for FreeBSD.  Currently, `MADV_FREE` forces the kernel to put pages in a read-only state (with associated TLB shootdown costs) and then put them back in a read-write state (or CoW fault them from the zero page) if they are not used.  If we had a `MADV_LAZY_DECOMMIT` and a `MADV_RECOMMIT`, the kernel could just mark a page as safe to reclaim and would only ever need to actually do the reclaim if the memory pressure grew sufficiently that `MADV_FREE` would have taken the page away.  We'd be making slightly stronger API guarantees than `MADV_FREE`, because we'd be required to do the `MADV_RECOMMIT` thing before reuse.  If the page hadn't been stolen, the kernel would just have to acquire a lock and clear the flag.  If it had, then we'd get the CoW zero page back (or possibly a real page if we did something like `MADV_RECOMMIT | MADV_WILLNEED`.

**Comment by mjp41** [comment]
I think LargeAlloc is thread safe, it is all using the MPMCstacks, so everything should be fine. Nothing we decommit in this process is thread local, it is all global to the allocator.

Re: OS API, I had been thinking a lazy decommit/recommit would be really useful, i.e.  something that avoids the TLB shootdown would be great.

**Comment by davidchisnall** [comment]
Actually, on FreeBSD, it looks as if `MADV_FREE` does the right thing.  It (more or less) just clears the modified flag on the page, so the swap pager can then discard the page (the pager then sees an unmodified page, marks it as read-only, and then re-checks the dirty bit and throws away the physical page).  This means that there are no TLB shootdowns for `MADV_FREE` unless we hit low memory, which explains why `MADV_FREE` is so fast on FreeBSD.
