### ISSUE TITLE
How to adopt larger PAGE_SIZE?

### ISSUE THREAD

**Issue by SchrodingerZhu** [microsoft/snmalloc#169]
I was trying to port `snmalloc` to a platform with larger page size; I spotted it seems that the OS_PAGE_SIZE is hard-coded. I tried changing the default value, however, alignment checking is failed then. 

is there any instruction to follow to port this library to an environment with a larger `PAGE_SIZE`?

**Comment by mjp41** [comment]
@davidchisnall do you have thoughts on this?

What platform are you trying to port this too?

**Comment by davidchisnall** [comment]
I think everything that depends on the page size ought to be keyed off the `OS_PAGE_SIZE` value.  If there are some places where we're not doing it correctly, then those are bugs.  

If that is fixed, I think that supporting larger page sizes ought to be relatively easy.  We use that value as the minimum size that we can commit physical pages, but we typically do this in 64KiB chunks irrespective of the underlying page size.  We probably want to inspect some of the logic to make sure that, for example, an 8KiB page size doesn't make chunks 128KiB instead of 64KiB.

**Comment by SchrodingerZhu** [comment]
I should have given my example:
set `OS_PAGE_SIZE` to `16384`.
Then this check will fail:
https://github.com/microsoft/snmalloc/blob/c09b2468f97936af2252c03f7bbc51876308d4ba/src/mem/alloc.h#L734

**Comment by davidchisnall** [comment]
That looks as if our jump from small to medium size classes is assuming a 4KiB page.  As the comment says, we assume that medium sizes are multiples of a page and it looks as if we're not using `OS_PAGE_SIZE` in the calculation of this.

I wonder if we actually want to bump the slab size on systems with larger pages.  The slab size is currently 64KiB, I'm not sure what the impact would be on making it `16*OS_PAGE_SIZE`.  We'd see more fragmentation on these systems, but hopefully that wouldn't translate to increased TLB pressure and it would only really make a difference if you had a lot of threads that all allocated a small number of objects with a large number of different (smaller-than-a-page) sizes.

**Comment by nwf** [comment]
What a timely report.  I just ran into similar issues myself; my home workstation is a Debian powerpc64 box with 64KiB pages, apparently (who knew?).

Building with a minimal PAL and `OS_PAGE_SIZE` of 4KiB, a whole lot of things appear to work, but the first failure I noticed was in `func-malloc-1` and is that `mprotect()` in `notify_using` is called on a 4KiB but not 64KiB aligned address.  Anyway, I wonder if `OS_PAGE_SIZE` should be moved over to `AAL`/`PAL` rather than `allocconfig`?

**Comment by mjp41** [comment]
So I think the requirement that medium allocations is a multiple of page size is no longer relevant. At one stage we allowed for the memory associated to a medium allocation to be decommitted.  But those code paths weren't tested, and didn't perform well, so I removed them.

>  Anyway, I wonder if OS_PAGE_SIZE should be moved over to AAL/PAL rather than allocconfig?

That makes sense.  I am not focussed on `snmalloc` for the next few weeks at least, but will happily review a PR.

**Comment by nwf** [comment]
> The slab size is currently 64KiB, I'm not sure what the impact would be on making it `16*OS_PAGE_SIZE`.

Unfortunately, this isn't completely trivial as `(1 << SLAB_SIZE) - 1` currently needs to fit in a `uint16_t`.  I went through and moved things over to a
```
  using IntraSlabIndex =
    std::conditional_t<(Pal::OS_PAGE_SIZE > 0x1000), uint32_t, uint16_t>;
```
but I'm not sure that's the greatest approach.  Separately, increasing `SLAB_BITS` past 16 requires either tamping down on `SLAB_COUNT_BITS` or revising some as-yet mysterious to me code that declares `static_assert(SUPERSLAB_BITS <= 24, "The following code assumes 24 bits");`.

I think there were still places at least asserting that medium-size objects were page aligned and ISTR one attempt to `madvise` one, still, which is why I was fiddling with `SLAB_BITS`.  But it was getting kind of late at night and I no longer exactly remember; I'll try again and report with more detail.

**Comment by SchrodingerZhu** [comment]
I think this is already resolved now?

**Comment by mjp41** [comment]
I think this can be closed?  @nwf you have snmalloc working on a 64kib machine?

**Comment by nwf** [comment]
Yes, ppc64le Debian.
