### ISSUE TITLE
Add a short small slab to MediumSlab headers if there's room?

### ISSUE THREAD

**Issue by nwf** [microsoft/snmalloc#238]
On some architecture/pal combinations (e.g., PowerPC/Linux), pages are 64KiB and the MediumSlab headers are... not.  Despite 3d3b048776fd576c725a06bd8c4432c50abca81b, many size classes are going to leave a large, physically-backed region of wasted space between the MediumSlab header and its first contained allocation.  Perhaps we could fit a short slab in there as we do with the space between the Superslab header and its Slabs.

**Comment by mjp41** [comment]
This is an interesting idea, but will complicate the allocator considerable on the `dealloc` path.  Particularly, for sized deallocations, where we won't know the meta-data layout without branching on whether this is a Medium slab or Super slab.

I guess we could design the Medium slab, to contain a Superslab like structure for the first few slabs, so that there isn't a branch. Then we can use those slabs if rounding dictates it makes sense.

I think given the complexity this would add I would like some data that it would have a useful impact on a platform.

**Comment by mjp41** [comment]
Given the redesign, this no longer seems relevant.
