### ISSUE TITLE
How to use the new hardening features

### ISSUE THREAD

**Issue by Zeblote** [microsoft/snmalloc#523]
I am not seeing how to use the new hardening features when including snmalloc as a header-only library on Windows. There doesn't seem to be any #define or similar mentioned in the documentation? Is it just enabled by default?

**Comment by mjp41** [comment]
It is enabled with 
```
SNMALLOC_CHECK_CLIENT
```
I will update the documentation.  That does not enable the memcpy protection.

On Windows the performance of the memcpy protection is not great due to the way virtual memory works.  We can't map a large accessible zero range without actually committing the memory.  We could add a Vectored Exception handler, but then it is going to harm the debugging experience.

**Comment by Zeblote** [comment]
Thanks! I made a quick test comparing this new version against FMallocBinned2, though whether this can be considered a proper benchmark is questionable. Same integration code as my previous issue https://github.com/microsoft/snmalloc/issues/478.

FMallocBinned2, memory usage:
Start game
![perfmon_2022-05-10_17-02-33](https://user-images.githubusercontent.com/6764788/167661358-5170176f-bf6d-44af-b20b-5d0bbdad362d.png)

Open map
![perfmon_2022-05-10_17-02-51](https://user-images.githubusercontent.com/6764788/167661371-359ac7e0-1dc0-48ad-ab75-71cc1c3bff5d.png)

Load large save
![perfmon_2022-05-10_17-03-42](https://user-images.githubusercontent.com/6764788/167661378-fc1c4b9f-6d92-4bfa-8320-df04a3d3d4e1.png)

Clear large save
![perfmon_2022-05-10_17-04-27](https://user-images.githubusercontent.com/6764788/167661386-349f69e6-098f-46c8-bb3d-82390edce4db.png)

Load large save again
![perfmon_2022-05-10_17-05-24](https://user-images.githubusercontent.com/6764788/167661398-adf01f3a-88f7-4f03-8a6f-c2c1c06c53ac.png)

snmalloc 0.6 with SNMALLOC_CHECK_CLIENT, memory usage:
Start game
![perfmon_2022-05-10_17-15-10](https://user-images.githubusercontent.com/6764788/167663683-c639a67e-164b-483c-ae79-b401082155b9.png)

Open map
![perfmon_2022-05-10_17-15-24](https://user-images.githubusercontent.com/6764788/167663701-51418304-6290-4d40-bf89-149ee6c11cae.png)

Load large save
![perfmon_2022-05-10_17-16-08](https://user-images.githubusercontent.com/6764788/167663716-d7b64a47-b06e-4434-a9df-6760dd8d46e7.png)

Clear large save
![perfmon_2022-05-10_17-17-22](https://user-images.githubusercontent.com/6764788/167663724-1eeb741d-b78f-419e-ad59-5634773c5faf.png)

Load large save again
![perfmon_2022-05-10_17-18-11](https://user-images.githubusercontent.com/6764788/167663732-59825ec3-e794-46bb-bca2-aedf1be86577.png)

It seems like it doesn't free unused memory nearly as much as the default unreal allocator. Overall usage is also a bit higher. This seems to be a clear win for FMallocBinned2.

FMallocBinned2, performance:
![Brickadia-Win64-Shipping_2022-05-10_17-05-45](https://user-images.githubusercontent.com/6764788/167663789-a96dccf0-74a5-48f6-a0d2-7b0a6a7cfa0b.png)

snmalloc 0.6 with SNMALLOC_CHECK_CLIENT, performance:
![Brickadia-Win64-Shipping_2022-05-10_17-18-24](https://user-images.githubusercontent.com/6764788/167663849-1df639cd-08f6-4149-b730-78f1e14190cb.png)

Only slightly slower on allocations, but much faster on deallocations. This seems to be a win for snmalloc overall.

 The game also seems to crash on exit when snmalloc is used but I haven't yet investigated why.

**Comment by Zeblote** [comment]
> On Windows the performance of the memcpy protection is not great due to the way virtual memory works. We can't map a large accessible zero range without actually committing the memory. We could add a Vectored Exception handler, but then it is going to harm the debugging experience.

Can you explain why this is required? Is it to support allocations from outside snmalloc?

For example, in Unreal Engine, there are over 1000 calls to FMemory::Memcpy, the absolute vast majority only ever operating on memory obtained from FMemory. It would probably be a good start to guard all of those.

**Comment by mjp41** [comment]
Yeah, it is to support allocations from outside snmalloc.  The key issue is "absolute vast majority", if one isn't and we crash because of it, then customers will get very annoyed.  For instance,

```C
   char buffer[256];
   memcpy(src, buffer, std::min(256, src_size));
```

This needs the stack allocation of `buffer` to not create an access violation when we look up the meta-data.  On Linux for instance, we `mmap` a 256GiB region of memory, and then any access is allowed.  On Windows, we `MEM_RESERVE`, a 256GiB region, and then `MEM_COMMIT` the bits that correspond to snmalloc allocations.  This means that accessing the meta-data on Windows for anything that doesn't correspond to an allocation will segfault.  There are three approaches we could take

*  Any attempt to access a meta-data that is not guaranteed to be snmalloc controlled causes a call to `MEM_COMMIT`.  This is the current implementation and is very slow.
*  We could install a VectoredExceptionHandler to detect accessing the meta-data when it is not committed, and commit it.  This is much cheaper, but leads to a poor debugging experience.  The debugger will probably trap the access violation before the handler, and lead users to believe that something is wrong when it isn't.
*  Install shared 2MiB zero pages for all the range outside that currently used by snmalloc.  This would incur a few MiB of commit charge for the associated page tables, and the shared large page.  It would not involve any exceptions, so debugging would be fine.  It is however a pretty complex change. 

I prototyped the third option a couple of years ago, and I think given the new refactoring in 0.6.0 it would fit quite nicely.  I don't currently have time to implement it though.

**Comment by Zeblote** [comment]
Oh, you're right. I completely forgot about stack allocations. Those are very common, so it would be unusable.

Hope you'll find time to implement a good performing solution at some point!
