### ISSUE TITLE
_msize is not provided as an override?

### ISSUE THREAD

**Issue by Naville** [microsoft/snmalloc#631]
Cross-posting from [Z3](https://github.com/Z3Prover/z3/issues/6890) and grepping through the source-code doesn't seem to provide an override for it

**Comment by mjp41** [comment]
We can certainly add a copy of 

https://github.com/microsoft/snmalloc/blob/7b597335aedc2c60b0174f6e67a7f7560f841760/src/snmalloc/override/malloc.cc#L37-L42

for `_msize`.  Could you point me at instructions for Z3 set up you are using on Windows, so I can try to replicated to check I have fixed it.

**Comment by davidchisnall** [comment]
If I read that thread correctly, `_msize` is the Windows spelling for `malloc_usable_size` and the problem is that some code is calling it, but it's not an exported symbol from snmalloc and so you get problems mixing and matching.

The Windows heap surface is quite large.  We don't currently provide implementations for most of its functions (in particular, the ones that let you ask for memory where some offset within the allocation is aligned look useful in some situations but we don't provide them at all).

I don't think that we're opposed to providing a complete drop-in replacement for the Windows heap APIs (or arbitrary subsets).  Patches to add more API surface coverage are welcome.  We already have [shims for jemalloc's non-standard APIs](https://github.com/microsoft/snmalloc/blob/main/src/snmalloc/override/jemalloc_compat.cc), so adding shims for other non-standard APIs is definitely in scope.

**Comment by Naville** [comment]
> We can certainly add a copy of
> 
> https://github.com/microsoft/snmalloc/blob/7b597335aedc2c60b0174f6e67a7f7560f841760/src/snmalloc/override/malloc.cc#L37-L42
> 
> for `_msize`. Could you point me at instructions for Z3 set up you are using on Windows, so I can try to replicated to check I have fixed it.

So far, just Z3 + snmalloc and create any ``z3::context`` instance will reach the troublesome path it seems.

Should be trivially triggerable

**Comment by Naville** [comment]
On Z3 side, [#6321](https://github.com/Z3Prover/z3/pull/6321/files) seems to be the initial introduction of ``malloc_usable_size``,  then @nunoplopes 's patch seems to enabled that line on Windows which defaults to use ``_msize`` that's not exported by snmalloc

**Comment by Naville** [comment]
```
libucrt.lib(msize.obj) : error LNK2005: _msize already defined in LLVMSupport.lib(malloc.cc.obj)
bin\llvm-tblgen.exe : fatal error LNK1169: one or more multiply defined symbols found
```
@mjp41 I'm unfortunately not an Windows export, but why building with LLVM + snmalloc + this patch results in this error. yet everything works fine without it

**Comment by SchrodingerZhu** [comment]
so it is not a weak symbol in ucrt?

**Comment by mjp41** [comment]
This might be related

https://bugs.chromium.org/p/chromium/issues/detail?id=915016

If you can send me instructions for how you are building this. I can try to replicate.

**Comment by Naville** [comment]
```
-DLLVM_USE_CRT_RELWITHDEBINFO=MT
-DLLVM_INTEGRATED_CRT_ALLOC="snmalloc"
```
and build llvm-tblgen target

**Comment by Naville** [comment]
My exact setup is LLVM 12.0.1 with the configuration.
LLVM12's buildsystem supports only snmalloc 0.5.3 so I manually added this to that version of snmalloc:

```c++
#ifdef _WIN32

  SNMALLOC_EXPORT
  size_t SNMALLOC_NAME_MANGLE(_msize)(void* ptr)
  {
    return Alloc::alloc_size(ptr);
  }
#endif
```
Can confirm the issue reliably reproduces if this code snippet is added and disappear if commented out

**Comment by Naville** [comment]
> This might be related
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=915016
> 
> If you can send me instructions for how you are building this. I can try to replicate.

This seems to work. I'll try more across our build infrastructure
