### ISSUE TITLE
Possible nullptr access

### ISSUE THREAD

**Issue by anakrish** [microsoft/snmalloc#657]
The following code indicates that on line 184 `n_tame` could be null but goes on to access it unchecked on line 190.

https://github.com/microsoft/snmalloc/blob/d9bca644260847f3b325f4d0e12f0360ed1c0dac/src/snmalloc/mem/freelist.h#L182-L191

**Comment by mjp41** [comment]
@anakrish thanks for looking at this.  I think in this case it is okay.

I assume you are referring to:
```C++
Aal::prefetch(&(n_tame->next_object));
```
Because of the `&` and `->` this boils down to `n_tame + offsetof(next_object)`. So in this case, we will be sending a prefetch hint to the `null` page. My understanding is that prefetch should not cause an access violation.

**Comment by anakrish** [comment]
Ah, makes sense.

**Comment by mjp41** [comment]
So UBSan agreed with you that this was undefined behaviour, but the CI wasn't properly blocked on UBSan.  I have ended up changing it in 

https://github.com/microsoft/snmalloc/pull/662/commits/d3b284cfcacb03a83dd9c53ce90c6871dd1eb758

as part of #662.
